Ext.define('GSmartApp.model.TVSOrgStatusShow', {
    extend: 'GSmartApp.model.Base',

    fields: [
        'id', 
        'org1_name',
        'org1_orderlist',
        'org1_amountcutsum',
        'org1_amountinputsum',
        'org1_amountoutputsum',
        'org1_percentcomplete',
        'org1_golivedate',

        'org2_name',
        'org2_orderlist',
        'org2_amountcutsum',
        'org2_amountinputsum',
        'org2_amountoutputsum',
        'org2_percentcomplete',
        'org2_golivedate',

        'org3_name',
        'org3_orderlist',
        'org3_amountcutsum',
        'org3_amountinputsum',
        'org3_amountoutputsum',
        'org3_percentcomplete',
        'org3_golivedate',

        'org4_name',
        'org4_orderlist',
        'org4_amountcutsum',
        'org4_amountinputsum',
        'org4_amountoutputsum',
        'org4_percentcomplete',
        'org4_golivedate',

        'org5_name',
        'org5_orderlist',
        'org5_amountcutsum',
        'org5_amountinputsum',
        'org5_amountoutputsum',
        'org5_percentcomplete',
        'org5_golivedate',

        'org6_name',
        'org6_orderlist',
        'org6_amountcutsum',
        'org6_amountinputsum',
        'org6_amountoutputsum',
        'org6_percentcomplete',
        'org6_golivedate',

        'org7_name',
        'org7_orderlist',
        'org7_amountcutsum',
        'org7_amountinputsum',
        'org7_amountoutputsum',
        'org7_percentcomplete',
        'org7_golivedate',

        'org8_name',
        'org8_orderlist',
        'org8_amountcutsum',
        'org8_amountinputsum',
        'org8_amountoutputsum',
        'org8_percentcomplete',
        'org8_golivedate',

        'org9_name',
        'org9_orderlist',
        'org9_amountcutsum',
        'org9_amountinputsum',
        'org9_amountoutputsum',
        'org9_percentcomplete',
        'org9_golivedate',

        'org10_name',
        'org10_orderlist',
        'org10_amountcutsum',
        'org10_amountinputsum',
        'org10_amountoutputsum',
        'org10_percentcomplete',
        'org10_golivedate',

        'org11_name',
        'org11_orderlist',
        'org11_amountcutsum',
        'org11_amountinputsum',
        'org11_amountoutputsum',
        'org11_percentcomplete',
        'org11_golivedate',

        'org12_name',
        'org12_orderlist',
        'org12_amountcutsum',
        'org12_amountinputsum',
        'org12_amountoutputsum',
        'org12_percentcomplete',
        'org12_golivedate',

        'org13_name',
        'org13_orderlist',
        'org13_amountcutsum',
        'org13_amountinputsum',
        'org13_amountoutputsum',
        'org13_percentcomplete',
        'org13_golivedate',
		
        'org14_name',
        'org14_orderlist',
        'org14_amountcutsum',
        'org14_amountinputsum',
        'org14_amountoutputsum',
        'org14_percentcomplete',
        'org14_golivedate',
		
        'org15_name',
        'org15_orderlist',
        'org15_amountcutsum',
        'org15_amountinputsum',
        'org15_amountoutputsum',
        'org15_percentcomplete',
        'org15_golivedate',

        'org16_name',
        'org16_orderlist',
        'org16_amountcutsum',
        'org16_amountinputsum',
        'org16_amountoutputsum',
        'org16_percentcomplete',
        'org16_golivedate'	
    ]
});
