Ext.define('GSmartApp.view.stockoutforcheck.Stockout_ForCheck_Edit_ToVai_Main', {
    extend: 'Ext.form.Panel',
    xtype: 'Stockout_ForCheck_Edit_ToVai_Main',
    id: 'Stockout_ForCheck_Edit_ToVai_Main',
    reference: 'Stockout_ForCheck_Edit_ToVai_Main',
    controller: 'Stockout_ForCheck_Edit_ToVai_MainController',
    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    requires: [
        'Ext.Toast',
        'Ext.Responsive',
        'Ext.dataview.listswiper.ListSwiper'
    ],

    items:[
        {
            xtype: 'container',
            // flex:1,
            // height: 100,
            // docked: 'bottom',
            layout: 'hbox',
            items:[
                {
                    xtype: 'combobox',
                    itemId: 'cbbox_pkl_stockout_order_dId',
                    // reference: 'cboorgto',
                    editable: false,
                    readOnly: true,
                    // cls: 'notEditable',
                    bind:{
                        store:'{Stockout_order_d_store}',
                        value:'{pkl_stockout_order_dId}'
                    },
                    displayField: 'skucode',
                    valueField: 'id',
                    // label: 'Nơi giao:',
                    // disabled: true,
                    labelWidth: 85,
                    flex: 1,
                    padding: 2,
                    hidden: true
                },
                {
                    xtype: 'textfield',
                    itemId: 'maPklFilter',
                    // label: 'Mã hàng:',
                    // labelWidth: 85,
                    margin: '5 5 1 5',
                    // padding: 6,
                    flex: 1,
                    // width: '100%',
                    // minWidth: 80,
                    // maxWidth: 200,
                    textAlign: 'left',
                    placeholder: 'Tìm kiếm nhanh ... (theo lot)',
                    // editable: false,
                    // readOnly: true,
                    clearable: false,
                    cls: 'searchField',
                    bind: {
                        value: '{maPklFilter}'
                    },
                    listeners: {
                        keyup: 'onmaPklFilterKeyup',
                        buffer: 500
                    }
                },
            ]
        },
        
        {
            margin: 1,
            flex: 1,
            xtype: 'Stockout_ForCheck_Edit_ToVai',
        },

        {
            xtype: 'container',
            // flex:1,
            // height: 100,
            // docked: 'bottom',
            layout: 'vbox',
            items:[
                {
                    layout: 'hbox',
                    border: false,
                    width: '100%',
                    items:[
                        {
                            xtype: 'textfield',
                            margin: 1,
                            border: true,
                            cls: 'my-textfield',
                            itemId: 'lotnumberTxt',
                            // label: 'Màu:',
                            // labelWidth: 85,
                            flex: 1,
                            minWidth: 80,
                            // maxWidth: 130,
                            textAlign: 'left',
                            placeholder: 'Số LOT',
                            // editable: false,
                            // readOnly: true,
                            // clearable: false,
                            // cls: 'notEditable',
                            bind: {
                                value: '{objPkl.lotnumber}'
                            },
                            listeners: {
                                change: 'onlotnumberTxtType',
                                focusleave: 'onlotnumberTxtAndpackageidTxtleave'
                            }
                        },
                        {
                            xtype: 'numberfield',
                            margin: 1,
                            border: true,
                            cls: 'my-textfield',
                            itemId: 'packageidTxt',
                            // label: 'Màu:',
                            // labelWidth: 85,
                            flex: 1,
                            minWidth: 80,
                            // maxWidth: 130,
                            textAlign: 'left',
                            placeholder: 'Số cây',
                            // editable: false,
                            // readOnly: true,
                            // clearable: false,
                            // cls: 'notEditable',
                            bind: {
                                value: '{objPkl.packageid}'
                            },
                            listeners: {
                                focusleave: 'onlotnumberTxtAndpackageidTxtleave'
                            },
                            stepValue: 0.1,
                        },
                        {
                            xtype:'button',
                            // text: 'Xác nhận',
                            // flex: 1,
                            // minWidth: 80,
                            // maxWidth: 130,
                            // width: 45,
                            margin: 1,
                            iconCls: 'x-fa fa-check',
                            itemId:'btnCheck',
                            ui: 'action',
                            bind: {
                                disabled: '{!isobjPklSelected}'
                            }
                        },   
                    ]
                },
                {
                    layout: 'hbox',
                    border: false,
                    width: '100%',
                    items:[
                        {
                            xtype: 'numberfield',
                            margin: 1,
                            border: true,
                            cls: 'my-textfield',
                            itemId: 'mTxt',
                            // label: 'Màu:',
                            // labelWidth: 85,
                            flex: 1,
                            minWidth: 80,
                            // maxWidth: 130,
                            textAlign: 'left',
                            placeholder: 'Dài kiểm (M)',
                            // editable: false,
                            // readOnly: true,
                            // clearable: false,
                            // cls: 'notEditable',
                            bind: {
                                value: '{objPkl.metcheck}',
                                hidden: '{isMetColumnHidden}',
                            },
                            stepValue: 0.1,
                        },
                        {
                            xtype: 'numberfield',
                            margin: 1,
                            border: true,
                            cls: 'my-textfield',
                            itemId: 'yTxt',
                            // label: 'Màu:',
                            // labelWidth: 85,
                            flex: 1,
                            minWidth: 80,
                            // maxWidth: 130,
                            textAlign: 'left',
                            placeholder: 'Dài kiểm (Y)',
                            // editable: false,
                            // readOnly: true,
                            // clearable: false,
                            // cls: 'notEditable',
                            bind: {
                                value: '{objPkl.ydscheck}',
                                hidden: '{isYdsColumnHidden}',
                            },
                            stepValue: 0.1,
                        },
                        {
                            xtype: 'numberfield',
                            border: true,
                            cls: 'my-textfield',
                            margin: 1,
                            itemId: 'widthYdsCheckTxt',
                            // label: 'Màu:',
                            // labelWidth: 85,
                            flex: 1,
                            // maxWidth: 130,
                            textAlign: 'left',
                            placeholder: 'Khổ kiểm (Y)',
                            // editable: false,
                            // readOnly: true,
                            // clearable: false,
                            // cls: 'notEditable',
                            bind: {
                                value: '{objPkl.width_yds_check}',
                                hidden: '{isYdsColumnHidden}',
                            },
                            stepValue: 0.1,
                        },
                        {
                            xtype: 'numberfield',
                            border: true,
                            cls: 'my-textfield',
                            margin: 1,
                            itemId: 'widthMetCheckTxt',
                            // label: 'Màu:',
                            // labelWidth: 85,
                            flex: 1,
                            // maxWidth: 130,
                            textAlign: 'left',
                            placeholder: 'Khổ kiểm (M)',
                            // editable: false,
                            // readOnly: true,
                            // clearable: false,
                            // cls: 'notEditable',
                            bind: {
                                value: '{objPkl.width_met_check}',
                                hidden: '{isMetColumnHidden}',
                            },
                            stepValue: 0.1,
                        },
                        {
                            xtype:'button',
                            iconCls: 'x-fa fa-plus',
                            // itemId:'',
                            ui: 'action',
                            margin: 1,
                            style: 'visibility: hidden;'
                        },
                    ]
                },
                // {
                //     layout: 'hbox',
                //     border: false,
                //     width: '100%',
                //     items:[
                //         {
                //             xtype: 'numberfield',
                //             margin: 1,
                //             border: true,
                //             cls: 'my-textfield',
                //             itemId: 'mTxt',
                //             // label: 'Màu:',
                //             // labelWidth: 85,
                //             flex: 1,
                //             minWidth: 80,
                //             // maxWidth: 130,
                //             textAlign: 'left',
                //             placeholder: 'Dài kiểm (M)',
                //             // editable: false,
                //             // readOnly: true,
                //             // clearable: false,
                //             // cls: 'notEditable',
                //             bind: {
                //                 value: '{objPkl.metcheck}',
                //                 hidden: '{isMetColumnHidden}',
                //             },
                //             stepValue: 0.1,
                //         },
                //         {
                //             xtype: 'numberfield',
                //             margin: 1,
                //             border: true,
                //             cls: 'my-textfield',
                //             itemId: 'yTxt',
                //             // label: 'Màu:',
                //             // labelWidth: 85,
                //             flex: 1,
                //             minWidth: 80,
                //             // maxWidth: 130,
                //             textAlign: 'left',
                //             placeholder: 'Dài kiểm (Y)',
                //             // editable: false,
                //             // readOnly: true,
                //             // clearable: false,
                //             // cls: 'notEditable',
                //             bind: {
                //                 value: '{objPkl.ydscheck}',
                //                 hidden: '{isYdsColumnHidden}',
                //             },
                //             stepValue: 0.1,
                //         },
                //         {
                //             xtype: 'numberfield',
                //             border: true,
                //             cls: 'my-textfield',
                //             margin: 1,
                //             itemId: 'mOriginTxt',
                //             // label: 'Màu:',
                //             // labelWidth: 85,
                //             flex: 1,
                //             // maxWidth: 130,
                //             textAlign: 'left',
                //             placeholder: 'Dài phiếu (M)',
                //             // editable: false,
                //             // readOnly: true,
                //             // clearable: false,
                //             // cls: 'notEditable',
                //             bind: {
                //                 value: '{objPkl.metorigin}',
                //                 hidden: '{isMetColumnHidden}',
                //             },
                //             stepValue: 0.1,
                //         },
                //         {
                //             xtype: 'numberfield',
                //             border: true,
                //             cls: 'my-textfield',
                //             margin: 1,
                //             itemId: 'yOriginTxt',
                //             // label: 'Màu:',
                //             // labelWidth: 85,
                //             flex: 1,
                //             // maxWidth: 130,
                //             textAlign: 'left',
                //             placeholder: 'Dài phiếu (Y)',
                //             // editable: false,
                //             // readOnly: true,
                //             // clearable: false,
                //             // cls: 'notEditable',
                //             bind: {
                //                 value: '{objPkl.ydsorigin}',
                //                 hidden: '{isYdsColumnHidden}',
                //             },
                //             stepValue: 0.1,
                //         },
                //         {
                //             xtype:'button',
                //             iconCls: 'x-fa fa-plus',
                //             // itemId:'',
                //             ui: 'action',
                //             margin: 1,
                //             style: 'visibility: hidden;'
                //         },
                //     ]
                // },
                // {
                //     layout: 'hbox',
                //     border: false,
                //     width: '100%',
                //     items:[
                //         {
                //             xtype: 'numberfield',
                //             border: true,
                //             cls: 'my-textfield',
                //             margin: 1,
                //             itemId: 'widthYdsCheckTxt',
                //             // label: 'Màu:',
                //             // labelWidth: 85,
                //             flex: 1,
                //             // maxWidth: 130,
                //             textAlign: 'left',
                //             placeholder: 'Khổ kiểm (Y)',
                //             // editable: false,
                //             // readOnly: true,
                //             // clearable: false,
                //             // cls: 'notEditable',
                //             bind: {
                //                 value: '{objPkl.width_yds_check}',
                //                 hidden: '{isYdsColumnHidden}',
                //             },
                //             stepValue: 0.1,
                //         },
                //         {
                //             xtype: 'numberfield',
                //             border: true,
                //             cls: 'my-textfield',
                //             margin: 1,
                //             itemId: 'widthYdsTxt',
                //             // label: 'Màu:',
                //             // labelWidth: 85,
                //             flex: 1,
                //             // maxWidth: 130,
                //             textAlign: 'left',
                //             placeholder: 'Khổ phiếu (Y)',
                //             // editable: false,
                //             // readOnly: true,
                //             // clearable: false,
                //             // cls: 'notEditable',
                //             bind: {
                //                 value: '{objPkl.width_yds}',
                //                 hidden: '{isYdsColumnHidden}',
                //             },
                //             stepValue: 0.1,
                //         },
                //         {
                //             xtype: 'numberfield',
                //             border: true,
                //             cls: 'my-textfield',
                //             margin: 1,
                //             itemId: 'widthMetCheckTxt',
                //             // label: 'Màu:',
                //             // labelWidth: 85,
                //             flex: 1,
                //             // maxWidth: 130,
                //             textAlign: 'left',
                //             placeholder: 'Khổ kiểm (M)',
                //             // editable: false,
                //             // readOnly: true,
                //             // clearable: false,
                //             // cls: 'notEditable',
                //             bind: {
                //                 value: '{objPkl.width_met_check}',
                //                 hidden: '{isMetColumnHidden}',
                //             },
                //             stepValue: 0.1,
                //         },
                //         {
                //             xtype: 'numberfield',
                //             border: true,
                //             cls: 'my-textfield',
                //             margin: 1,
                //             itemId: 'widthMetTxt',
                //             // label: 'Màu:',
                //             // labelWidth: 85,
                //             flex: 1,
                //             // maxWidth: 130,
                //             textAlign: 'left',
                //             placeholder: 'Khổ phiếu (M)',
                //             // editable: false,
                //             // readOnly: true,
                //             // clearable: false,
                //             // cls: 'notEditable',
                //             bind: {
                //                 value: '{objPkl.width_met}',
                //                 hidden: '{isMetColumnHidden}',
                //             },
                //             stepValue: 0.1,
                //         },
                //         {
                //             xtype:'button',
                //             iconCls: 'x-fa fa-plus',
                //             // itemId:'',
                //             ui: 'action',
                //             margin: 1,
                //             style: 'visibility: hidden;'
                //         },
                //     ]
                // },
            ]
        }
    ]
});