Ext.define('GSmartApp.model.Stockout_d', {
    extend: 'GSmartApp.model.Base',
    idProperty: 'idx',
    fields: [
        {name: 'id'},
        {name: 'idx'},
        'orgrootid_link',
        'stockoutid_link',
        'pordercode',
        {name: 'stockoutdate', type: 'date', dateFormat: 'c'},
        'skuid_link',
        'mainskucode',
        'skucode',
        'skuname',
        'product_code',
        'product_name',
        'skutype',
        'skutypeid_link',
        'colorid_link',
        'color_name',
        'sizeid_link',
        'size_name',
        'color_code',
        'unitid_link',
        'unit_name',
        'totalorder_design',
        'totalorder_tech',
        'widthorder',
        {name: 'totalpackage', type: 'int'},
        {name: 'totalpackage_req', type: 'int'},
        'listpackage',
        'totalydsorigin',
        'totalpackagecheck',
        'totalydscheck',
        'totalpackageprocessed',
        'totalydsprocessed',
        'totalerror',
        {
            name: 'totaldif',
            calculate: function(data) {
                return data.totalorder_tech - data.totalydsprocessed;
            }
        },          
        'unitprice',
        'totalprice',
        'p_skuid_link',
        'status',
        'extrainfo',
        'usercreateid_link',
        {name: 'timecreate', type: 'date', dateFormat: 'c'},
        'lastuserupdateid_link',
        {name: 'lasttimeupdate', type: 'date', dateFormat: 'c'},
        'totalmet_origin',
        'totalmet_check',
        'totalmet_processed',
        'totalmet_stockout',
    ],
    hasMany : {model: 'Stockout_pklist', name: 'stockoutpklist'}
});
