Ext.define('GSmartApp.model.Stockout', {
    extend: 'GSmartApp.model.Base',
    idProperty: 'idx',
    fields: [
        {name: 'id'},
        {name: 'idx', type: 'int'},
        'orgrootid_link',
        'stockoutorderid_link',
        'stockoutcode',
        {name: 'stockoutdate', type: 'date', dateFormat: 'c'},
        'stockouttypeid_link',
        'stockouttype_name',
        'stockoutorderid_link',
        'porderid_link',
        'pordercode',
        'p_skuid_link',
        'p_skucode',
        'invoice_number',
        'invoice_paymentype',
        {name: 'invoice_date', type: 'date', dateFormat: 'c'},
        'invoice_paymentdue',
        'vat_typeid_link',
        'vat_sample',
        'vat_symbol',
        'vat_number',
        {name: 'vat_date', type: 'date', dateFormat: 'c'},
        'vat_currencyid_link',
        'vat_exchangerate',
        {name: 'vat_paymentduedate', type: 'date', dateFormat: 'c'},
        'customs_number',
        {name: 'customs_date', type: 'date', dateFormat: 'c'},
        'contract_number',
        'orgid_from_link',
        'org_from_name',
        'orgid_to_link',
        'org_to_name',
        'shipperson',
        'totalpackage',
        'totalyds',
        'total_product',
        'total_mainmaterial',
        'total_mainmaterial_check',
        'total_mainmaterial_processed',
        'total_mainmaterial_stockout',
        'total_liningmaterial',
        'total_liningmaterial_check',
        'total_liningmaterial_processed',
        'total_liningmaterial_stockout',
        'total_mex',
        'total_mex_check',
        'total_mex_processed',
        'total_mex_stockout',
        'total_mixmaterial',
        'total_mixmaterial_check',
        'total_mixmaterial_processed',
        'total_mixmaterial_stockout',
        'totalpackagecheck',
        'totalydscheck',
        'totalpackageprocessed',
        'totalydsprocessed',
        'totalm3',
        'totalnetweight',
        'totalgrossweight',
        'totalprice',
        'extrainfo',
        'status',
        'reason',
        'usercreateid_link',
        'usercreate_name',
        {name: 'timecreate', type: 'date', dateFormat: 'c'},
        'lastuserupdateid_link',
        {name: 'lasttimeupdate', type: 'date', dateFormat: 'c'},
    ],
    hasMany : {model: 'Stockout_d', name: 'stockoutd'}
});
